import SwiftUI
import SwiftData
import UserNotifications

// MARK: - In-App Language Engine
//
// Problem: NSBundle caches its language choice on first string access per process.
// Changing UserDefaults["AppleLanguages"] after any string has been read has no effect.
// Since Onboarding slides 1-5 read strings before language is chosen in slide 6,
// all NSLocalizedString calls in the current session would remain in the launch language.
//
// Solution: object_setClass installs LanguageBundle as Bundle.main's class.
// LanguageBundle.localizedString() reads from a stored lproj Bundle that we swap
// instantly when the user changes language — bypassing NSBundle's internal cache.
//
// English path: we load en.lproj as an explicit Bundle (not via super/Bundle.main),
// avoiding the xcstrings incompatibility that broke English in earlier iterations.
// en.lproj/Localizable.strings is generated by Xcode because "en" is in knownRegions.
//
// We also set UserDefaults["AppleLanguages"] so the correct language loads on cold launch
// before object_setClass is installed (belt-and-suspenders).

/// The active lproj bundle used for all NSLocalizedString lookups.
/// Updated immediately when the user changes language.
private var _activeBundle: Bundle = {
    let saved = UserDefaults.standard.string(forKey: "selectedLanguage") ?? ""
    return LanguageEngine.bundle(for: saved)
}()

enum LanguageEngine {
    /// Returns the lproj Bundle for the given language identifier.
    /// Falls back to en.lproj for English or unset, guaranteeing a real .strings file.
    static func bundle(for identifier: String) -> Bundle {
        // Candidates to try in order
        let candidates: [String]
        if identifier.isEmpty || identifier.hasPrefix("en") {
            candidates = ["en"]
        } else {
            let base = String(identifier.prefix(2))
            candidates = identifier == base ? [identifier] : [identifier, base, "en"]
        }
        for candidate in candidates {
            if let path = Bundle.main.path(forResource: candidate, ofType: "lproj"),
               let bundle = Bundle(path: path) {
                return bundle
            }
        }
        // Absolute fallback — should never be reached in a correctly built app
        return .main
    }

    /// Call this whenever the user changes language.
    /// Updates the active bundle immediately (mid-session) and persists for next launch.
    static func apply(_ identifier: String) {
        _activeBundle = bundle(for: identifier)
        // Persist for cold launch (before object_setClass is installed)
        if identifier.isEmpty || identifier.hasPrefix("en") {
            UserDefaults.standard.set(["en"], forKey: "AppleLanguages")
        } else {
            let base = String(identifier.prefix(2))
            let langs: [String] = identifier == base
                ? [identifier, "en"]
                : [identifier, base, "en"]
            UserDefaults.standard.set(langs, forKey: "AppleLanguages")
        }
    }
}

/// Bundle.main subclass that redirects all string lookups to _activeBundle.
/// Installed once via object_setClass — only affects Bundle.main, nothing else.
class LanguageBundle: Bundle, @unchecked Sendable {
    override func localizedString(forKey key: String,
                                  value: String?,
                                  table tableName: String?) -> String {
        // Always read from _activeBundle (the lproj bundle for the chosen language).
        // _activeBundle is never Bundle.main, so there is no recursion risk.
        return _activeBundle.localizedString(forKey: key, value: value, table: tableName)
    }
}

@main
struct capstone2App: App {
    @AppStorage("selectedLanguage") private var selectedLanguage = ""

    init() {
        // 1. Install the language bundle hook before any view or string loads.
        object_setClass(Bundle.main, LanguageBundle.self)
        // 2. Apply the saved language (updates _activeBundle and AppleLanguages).
        LanguageEngine.apply(
            UserDefaults.standard.string(forKey: "selectedLanguage") ?? ""
        )
        UNUserNotificationCenter.current().delegate = NotificationDelegate.shared
        SymptomReminderScheduler.scheduleIfAuthorized()
    }

    var body: some Scene {
        WindowGroup {
            ContentView()
                .onChange(of: selectedLanguage) { _, newValue in
                    // Swap _activeBundle immediately — all subsequent NSLocalizedString
                    // calls (including re-evaluated static vars) use the new language.
                    LanguageEngine.apply(newValue)
                }
        }
        .modelContainer(for: [SymptomEntry.self, Habit.self])
    }
}

// MARK: - Notification Delegate
class NotificationDelegate: NSObject, UNUserNotificationCenterDelegate {
    static let shared = NotificationDelegate()
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        completionHandler([.banner, .sound, .badge])
    }
}

// MARK: - Symptom Reminder Scheduler
struct SymptomReminderScheduler {
    static let notificationID = "daily.symptom.checkin"

    static func scheduleIfAuthorized() {
        UNUserNotificationCenter.current().getNotificationSettings { settings in
            guard settings.authorizationStatus == .authorized ||
                  settings.authorizationStatus == .provisional else { return }
            UNUserNotificationCenter.current().getPendingNotificationRequests { pending in
                guard !pending.contains(where: { $0.identifier == notificationID }) else { return }
                schedule()
            }
        }
    }

    static func schedule() {
        let content = UNMutableNotificationContent()
        content.title = NSLocalizedString("notif.symptom.title", comment: "")
        content.body  = NSLocalizedString("notif.symptom.body",  comment: "")
        content.sound = .default
        content.badge = 1
        var dc = DateComponents()
        dc.hour = 21; dc.minute = 0
        let request = UNNotificationRequest(
            identifier: notificationID,
            content: content,
            trigger: UNCalendarNotificationTrigger(dateMatching: dc, repeats: true)
        )
        UNUserNotificationCenter.current().add(request) { error in
            if let error { print("Reminder scheduling failed: \(error)") }
        }
    }

    static func cancel() {
        UNUserNotificationCenter.current().removePendingNotificationRequests(
            withIdentifiers: [notificationID])
    }
}
